export const RoutePaths = {
    HOME: '/',
    RESTAURANTS: '/restaurants',
    RESTAURANT: '/restaurants/:id',
    MY_RESTAURANTS: '/my-restaurants',
    MY_RESTAURANT_NEW: '/my-restaurants/new',
    MY_RESTAURANT_EDIT: '/my-restaurants/:id/edit',
    MY_RESTAURANT_BOOKINGS: '/my-restaurants/:id/bookings',
    MY_RESTAURANT_LAYOUT: '/my-restaurants/:id/layout',
    MY_RESTAURANT_DISH_NEW: '/my-restaurants/:restaurantId/dishes/new',
    MY_RESTAURANT_DISH_EDIT: '/my-restaurants/:restaurantId/dishes/:dishId/edit',
    DISH: '/dishes/:id',
    BOOKING: '/booking',
    PROFILE: '/profile',
    PROFILE_EDIT: '/profile/edit',
    LOGIN: '/login',
    REGISTRATION: '/registration',
    NOT_FOUND: '*',
} as const;
