export { HomePage } from "@/pages/home-page/HomePage";
export { RestaurantsPage } from "@/pages/restaurants-page/RestaurantsPage";
export { RestaurantPage } from "@/pages/restaurant-page/RestaurantPage";
export {  BookingPage } from "@/pages/booking-page/BookingPage";
export {  ProfilePage } from "@/pages/profile-page/ProfilePage";
export {  LoginPage } from "@/pages/login-page/LoginPage";
export {  RegistrationPage } from "@/pages/registration-page/RegistrationPage";
export {  DishPage } from "@/pages/dish-page/DishPage";
export {  NotFoundPage } from "@/pages/not-found-page/NotFoundPage";
